### ISSUE TITLE
requiring library in client side

### ISSUE THREAD

**Issue by kyledavelaar** [goto-bus-stop/ws-events#1]
The examples and API say to require 'ws-events' client side but I am getting an error when using 'require' in js code connected to my html page.  Is there a way to use this library so I can connect events from sockets in my server to events in scripts in my html?

**Comment by goto-bus-stop** [comment]
Hi! In order to use `require` in the browser, you first need to bundle your code with a tool like [browserify](http://browserify.org/). You can then include the bundled script in your html using a script tag (`<script src="/path/to/bundle.js"></script>`).
